docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - lsb-release
  - software-properties-common

nginx_conf_path: "/etc/nginx/sites-available/default"
nginx_root_path: "/var/www/html"

prometheus_data_path: "/opt/prometheus"
grafana_data_path: "/var/lib/grafana"
