---
- name: Configure Server with Monitoring Stack
  hosts: servers
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure Nginx for proxying services
      copy:
        dest: "/etc/nginx/sites-available/default"
        content: |
          server {
            listen 80;
            server_name localhost;

            location /myapp {
                proxy_pass http://localhost:8080;
                proxy_set_header Host $host;
            }
            location /prometheus {
                proxy_pass http://localhost:9090;
                proxy_set_header Host $host;
            }
            location /grafana {
                proxy_pass http://localhost:3000;
                proxy_set_header Host $host;
            }
            location /alertmanager {
                proxy_pass http://localhost:9093;
                proxy_set_header Host $host;
            }

            location / {
                root /var/www/html;
                index index.html index.htm;
            }
          }
      notify:
        - Check Nginx configuration
        - Restart Nginx

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - lsb-release
          - software-properties-common
        state: latest
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: Check Nginx configuration
      command: nginx -t

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

- name: Deploy common exporters
  hosts: all
  roles:
    - prometheus.prometheus.node_exporter
    - prometheus.prometheus.cadvisor
  tags:
    - exporters

- name: Setup Prometheus
  hosts: prometheus
  roles:
    - prometheus.prometheus.blackbox_exporter
    - prometheus.prometheus.prometheus
#    - prometheus.prometheus.alertmanager
  tags:
    - prometheus

- name: Deploy Grafana
  hosts: grafana
  roles:
    - grafana.grafana.grafana
  tags:
    - grafana
